FROM python:3.9-alpine
RUN apk add --no-cache gcc musl-dev linux-headers

COPY ./requirements.txt /src/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r /src/requirements.txt

COPY . /src
#or COPY ./index.html /usr/share/nginx/html/index.html

ENV MY_ENV=netology_nginx_05_09
WORKDIR src
EXPOSE 6060

CMD ['python', '-u', 'main.py', '--host', '0.0.0.0', '--port', '6060']
