FROM python:3.9-alpine
RUN apk add --no-cache gcc musl-dev linux-headers

COPY ./requirements.txt /stocks_products/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r /stock_products/requirements.txt

COPY . /stocks_products

ENV MY_ENV=/.env

WORKDIR stocks_products
EXPOSE 6060
RUN python manage.py migrate
CMD ['python', 'manage.py', 'runserver', '0.0.0.0:6060']
